apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata: 
  name: web-ingress 
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: / 
spec: 
  ingressClassName: nginx 
  rules: 
  - host: skynet.com 
    http: 
      paths: 
      - path: /
        pathType: Prefix 
        backend: 
          service: 
            name: app1service 
            port: 
              number: 80
              
      - path: /lab 
        pathType: Prefix 
        backend: 
          service: 
            name: app1service 
            port: 
              number: 80 
      - path: /videos
        pathType: Prefix 
        backend: 
          service: 
            name: app2service 
            port: 
              number: 80 
      