apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
 containers:
   - name: dbcontainer
     image: mariadb:latest
     env:
       - name: MARIADB_DATABASE
         valueFrom:
           secretKeyRef:
             name: mysec
             key: db_name
       - name: MARIADB_ROOT_PASSWORD
         valueFrom:
           secretKeyRef:
             name: mysec
             key: root_password
